### ISSUE TITLE
smash.gg integration

### ISSUE THREAD

**Issue by snekery** [SilverStateEsports/SSEC-Nakamura-Theme#2]
Adding smash.gg integration will make pulling standings from SSE tournaments a lot simpler. I don't think that this would be done in the theme, but rather in a Ghost API, but it still needs to be determined on how we're gonna do this.

**Comment by 0x000NULL** [comment]
The theme would not be able to do this, rather the app its self would have to.

**Comment by snekery** [comment]
> The theme would not be able to do this, rather the app its self would have to.

Good to know. We'll go ahead and fork Ghost for this.
